hyperwallet/java-sdk

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java
Add account balances sdk 
https://jira.site1.hyperwallet.local/browse/HW-25476
=> Added account balances endpoint sdk

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletWebhookNotification.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletWebhookNotificationPaginationOptions.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletWebhookNotificationPaginationOptionsTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletWebhookNotificationTest.java
Added webhook notification resource endpoint sdk
=> Added webhook notification resource endpoint

README.md
The snippet before incorrectly used anonymous methods and didn't compile. Verified with Java 8.
=> Fix the demo snippet so that it actually compiles

src/main/java/com/hyperwallet/clientsdk/model/HyperwalletUser.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletUserTest.java
https://jira.site1.hyperwallet.local/browse/HW-47696
=> HW-47696 adding verificationStatus

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java
=> Fix doc typo

.travis.yml, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankAccount.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPaperCheck.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethod.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBankAccountTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPaperCheckTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodTest.java, src/test/resources/integration/createPaperCheck-response.json, src/test/resources/integration/getPaperCheck-response.json, src/test/resources/integration/listPaperChecks-response.json, src/test/resources/integration/updatePaperCheck-response.json
https://jira.site1.hyperwallet.local/browse/HW-54847
=> HW-54847 Remove Relationship field from Server SDK

src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodConfiguration.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodConfigurationTest.java
Removing fields - not required in V4
=> Hw 66755 transfer method config remove fields

README.md, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodConfiguration.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodConfigurationTest.java
Bug fix for TMC isRequired field. 
Added V3 SDK info on README.md
=> Bug fix and documentation update

src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankCard.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPayment.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBankCardTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPaymentTest.java
Adding missed fields to BankCard and Payments V3
=> Missed fields from BankCard and Payments V3

pom.xml, src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java
Please review the changes and approve if they look fine.
=> DTRUNWONE-82-Added headers for sdk-version, sdk-type and sdk-context id

src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/main/java/com/hyperwallet/clientsdk/util/Multipart.java, src/main/java/com/hyperwallet/clientsdk/util/MultipartRequest.java
Modified exception handling and successful response code processing
=> added additional response code and exception handling changed

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankAccount.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankAccountListPaginationOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankCard.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankCardListPaginationOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPayPalAccount.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPayPalAccountListPaginationOptions.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBankAccountListPaginationOptionsTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBankCardListPaginationOptionsTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBankCardTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPayPalAccountTest.java, src/test/resources/integration/listBankAccounts-request.txt, src/test/resources/integration/listBankAccounts-response.json
This is fir the ticket PPPLMER-94837 (https://engineering.paypalcorp.com/jira/browse/PPPLMER-94837) Please review the changes to accommodate missing query parameters in the following methods:
- List Bank Accounts
- List Bank Cards
- List Paypal Accounts
=> V3 java update query parameters

src/main/java/com/hyperwallet/clientsdk/util/HyperwalletMultipartUtils.java
Please approve the changes for uploading documents of multiple categories for KYC in Java-V3-SDK.
=> Uploading documents of multiple categories for KYC - Java-V3-DTRUNEONE-1405 -

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPaperCheck.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPaperCheckListPaginationOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPaymentListOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPrepaidCard.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPrepaidCardListPaginationOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethod.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferMethodListOptions.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletVenmoAccount.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletVenmoAccountListPaginationOptions.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPaperCheckTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPaymentListOptionsTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPrepaidCardTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletVenmoAccountTest.java, src/test/resources/integration/listPrepaidCards-request.txt, src/test/resources/integration/listPrepaidCards-response.json, src/test/resources/integration/listTransferMethods-response.json, src/test/resources/integration/listVenmoAccounts-request.txt, src/test/resources/integration/listVenmoAccounts-response.json, src/test/resources/integration/updatePrepaidCard-response.json
Please review the changes and approve for the list methods of the following resources:
- Venmo Accounts
- Prepaid Cards
- Paper Checks
- Transfer Methods
- Payments
=> V3-java-SDK-ppplmer 95761 update query parameters-PART B

src/main/java/com/hyperwallet/clientsdk/model/HyperwalletUser.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java
Ticket: https://engineering.paypalcorp.com/jira/browse/DTONBWTWO-514
Changes:
- Modified taxVerificationStatus clear function to use right key
- Modified tests to pass
New Test Results
Original test results
=> modified taxVerificationStatus to pass tests

CHANGELOG.md, README.md, pom.xml, src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java
Ticket: https://engineering.paypalcorp.com/jira/browse/DTONBWTWO-503
Changes: 
Updated Changelog
Updated Version
Note: Updated version in POM.xml, unsure if this is the correct/desired value
=> DTONBWTWO-503: updated version and changelog

CHANGELOG.md, README.md, pom.xml, src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java
Ticket : https://engineering.paypalcorp.com/jira/browse/DTONBWTWO-503
Changelog and version updated
=> Dtonbwtwo 503: java v3 prepare to deploy changes

pom.xml
Changed version to include "snapshot" in order to perform mvn deployment of new version
=> change version to snapshot

src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/resources/integration/updateUserTaxVerificationStatus-request.txt
=> updated IT test name and endpoint

src/test/java/com/hyperwallet/clientsdk/util/HyperwalletEncryptionTest.java
- Fixing unit test to include `Final` fields as they are updated to `Final` based on Intellij recommendations
=> DTRUNEONE-4371 Fixing unit test

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/main/java/com/hyperwallet/clientsdk/util/Message.java, src/main/java/com/hyperwallet/clientsdk/util/MultipartRequest.java, src/main/java/com/hyperwallet/clientsdk/util/Request.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletFT.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
Ticket: https://engineering.paypalcorp.com/jira/browse/DTPAYETWO-485
- Modified HTTP package and supplied it as a local util
- Modified Hyperwallet  and apiClient obj to take in proxy configuration as well as all HTTP methods
- Created relevant Functional and Unit Tests
Testing:
Used proxy and monitored status  of incoming requests and responses
=> DTPAYETWO-485: Proxy Implementation

README.md
Updating readme to include payload encryption section
=> DTRUNEONE-4371 Updating readme for payload encryption

README.md
Payload encryption documentation for V3
=> DTRUNEONE-4371 Updating readme for payload encryption V3

src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/main/java/com/hyperwallet/clientsdk/util/MultipartRequest.java, src/main/java/com/hyperwallet/clientsdk/util/Request.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletFT.java
Ticket: https://engineering.paypalcorp.com/jira/browse/DTPAYETWO-485
Modified HTTP util to take in authentication
Testing:
=> DTPAYETWO-485: V4 Proxy Implementation (AUTH)

README.md
=> DTPAYETWO-485: Updating Readme for Proxy Implementation

CHANGELOG.md, README.md, pom.xml, src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java
=> update to prepare for deployment

src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
**Changes in this pull request:**
- Updating logic to contains instead of equals when comparing JOSE content header
=> DTRUNEONE-4575 Update error handling

src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/main/java/com/hyperwallet/clientsdk/util/HyperwalletEncryption.java, src/main/java/com/hyperwallet/clientsdk/util/MultipartRequest.java, src/main/java/com/hyperwallet/clientsdk/util/Request.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletFT.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletEncryptionTest.java
Related to canva ask for proxy jws key load
=> added proxy field to encryption to allow jws key load through proxy

pom.xml, src/main/java/com/hyperwallet/clientsdk/util/Request.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletFT.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
Ticket: https://engineering.paypalcorp.com/jira/browse/PPPLMER-105727
Removed Purge Method and related functionality
Tested Http Methods and Proxy functionality and Java 13 compatibility
Testing Method for Java 11 and Java 13 compatibility:
- Build project using JDK 8 (mvn clean + install)
- Test Project (running mvn test and functional test)
- Switch JDK to v11/v13
- Test Project again
=> removed purge and adjusted for Java 13 compatability

CHANGELOG.md
Updated change log to account for missing change
=> added change and corrected spelling

CHANGELOG.md, README.md, src/main/java/com/hyperwallet/clientsdk/Hyperwallet.java, src/main/java/com/hyperwallet/clientsdk/util/HyperwalletApiClient.java, src/main/java/com/hyperwallet/clientsdk/util/MultipartRequest.java, src/main/java/com/hyperwallet/clientsdk/util/Request.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
- Support URL connection and read timeout with default value on Java SDK Rest V3
Sample code how to set timeout value:
```java
...
//300 milliseconds
int connectionTimeout = 300;
// 2 seconds  
int readTimout = 2000;
Hyperwallet client = new Hyperwallet(username, password, programToken, connectionTimeout, readTimout);
```
=> feature/DTSERWONE-846 Java SDK  v1.9.3 Rest V3- set http connection timeout 

.github/workflows/ci.yml, .github/workflows/documentation.yml
- Introduce GitHub action
- build and test on JAVA SDK 8 up to 18 version
- Report code coverage 
- Generate / Update Java Docs
https://coveralls.io/github/hyperwallet/java-sdk
Api doc: http://hyperwallet.github.io/java-sdk/
=> DTSERWONE-846 Introduce GitHub action

src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
JIRA Ticket: [DTSERWONE-846]
- Enhance the unit test to use mockserver instead of make real call
=> DTSERWONE-846 - Enhance Unit test to use mockserver

CHANGELOG.md, README.md
=> DTSERWONE-2066 - Prepare release 2.4.6

pom.xml
LI-36725
Bumpup version to fix security issue.
=> LI-36725 -Version bumup for Java_jason

src/main/java/com/hyperwallet/clientsdk/util/Request.java
LI-38226
closed connection to fix the infosec security vulnerability.
=> closed connection to fix security bug.

CHANGELOG.md, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBankCard.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/resources/integration/listBankCards-response.json
ticket: LI-50459
- Update Bank Card types
=> LI-50459 - Update Bank card types - Rest V4

src/main/java/com/hyperwallet/clientsdk/model/HyperwalletBalance.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletPayment.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletReceipt.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransfer.java, src/main/java/com/hyperwallet/clientsdk/model/HyperwalletTransferRefund.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletIT.java, src/test/java/com/hyperwallet/clientsdk/HyperwalletTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletBalanceTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletPaymentTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletReceiptTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletTransferRefundTest.java, src/test/java/com/hyperwallet/clientsdk/model/HyperwalletTransferTest.java, src/test/java/com/hyperwallet/clientsdk/util/HyperwalletApiClientTest.java
=> Deprecate Double to String

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml
New SCA and SAST tooling for Product Security. The replacement for Synposys Polaris and Blackduck.
This will run and report GHAS internally for vulnerability detection
=> Adding workflows

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml
GHAS Scans datadog Integration  to send metrics on scans status for codeql and sca
=> GHAS Scans datadog Integration 
